# Generated by Django 5.1 on 2026-05-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="core_user_email_38052c_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["is_active", "is_staff"], name="core_user_is_acti_ec7de3_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="core_user",
        ),
    ]
